import Navbar from "@/components/Navbar";
import "./globals.css";


export const metadata = {
  title: "hyggex assignment",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className="px-[4vw] py-[2vh] bg-[#F9F9F9]">
      <Navbar />
      {children}
      </body>
    </html>
  );
}
